# DataFrame Creation and Export

Builds a small DataFrame from scratch, inspects descriptive statistics, and exports it to multiple file formats (Excel, JSON, CSV).

In [6]:
import pandas as pd

## Create DataFrame

In [7]:
data = {
    'Name': ['Hamid Raza', 'Ali', 'Hassan', 'Hussain'],
    'Age': [21, 18, 16, 12],
    'Class': ['BSCS', 'Intermediate', 'First Year', 'O-level'],
}

df = pd.DataFrame(data)
df

         Name  Age         Class
0  Hamid Raza   21          BSCS
1         Ali   18  Intermediate
2      Hassan   16    First Year
3     Hussain   12       O-level

## Descriptive Statistics

In [8]:
df.describe()

             Age
count   4.000000
mean   16.750000
std     3.774917
min    12.000000
25%    15.000000
50%    17.000000
75%    18.750000
max    21.000000

## Export to Excel, JSON, and CSV

In [9]:
OUTPUT_DIR = '../outputs'

df.to_excel(f'{OUTPUT_DIR}/students.xlsx', index=False)
df.to_json(f'{OUTPUT_DIR}/students.json', indent=2)
df.to_csv(f'{OUTPUT_DIR}/students.csv', index=False)
print('Exported to outputs/students.xlsx, .json, .csv')

Exported to outputs/students.xlsx, .json, .csv

## Verify Exported Files

In [10]:
pd.read_excel(f'{OUTPUT_DIR}/students.xlsx')

         Name  Age         Class
0  Hamid Raza   21          BSCS
1         Ali   18  Intermediate
2      Hassan   16    First Year
3     Hussain   12       O-level

In [11]:
pd.read_json(f'{OUTPUT_DIR}/students.json')

         Name  Age         Class
0  Hamid Raza   21          BSCS
1         Ali   18  Intermediate
2      Hassan   16    First Year
3     Hussain   12       O-level

In [12]:
pd.read_csv(f'{OUTPUT_DIR}/students.csv')

         Name  Age         Class
0  Hamid Raza   21          BSCS
1         Ali   18  Intermediate
2      Hassan   16    First Year
3     Hussain   12       O-level